### ISSUE TITLE
ffmpeg+sdl+cocos2dx

### ISSUE THREAD

**Issue by zcgit** [hardman/AWLive#12]
你好，我近期也在使用ffmpeg+sdl+cocos2dx方案，现在显示视频和播放音频都OK了，但是经常声音有噪音，尤其是播放网络视频网速不好的时候，不知道你有遇到并解决过这类问题吗？

**Comment by hardman** [comment]
我是用这个方案播放本地视频。
网络视频的情况只是验证过能够播放，并没有正式使用过。。

**Comment by zcgit** [comment]
明白了，谢谢啊。
