### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by hxhowl** [hardman/AWLive#4]
ld: warning: ignoring file /Users/huangchp/Downloads/AWLive-master/clibs/3th-party/libyuv/lib/libyuv.a, missing required architecture x86_64 in file /Users/huangchp/Downloads/AWLive-master/clibs/3th-party/libyuv/lib/libyuv.a (2 slices)
Undefined symbols for architecture x86_64:
  "_ARGBToNV12", referenced from:
      -[AWGPUImageAVCaptureDataHandler newFrameReadyAtTime:atIndex:] in AWGPUImageAVCapture.o
  "_I420ToNV12", referenced from:
      -[AWVideoEncoder rotateNV12Data:] in AWVideoEncoder.o
  "_NV12ToI420Rotate", referenced from:
      -[AWVideoEncoder rotateNV12Data:] in AWVideoEncoder.o
ld: symbol(s) not found for architecture x86_64

**Comment by hxhowl** [comment]
似乎不能在模拟器上编译

**Comment by hardman** [comment]
不支持模拟器，请使用真机测试

**Comment by ryokinki** [comment]
你好: 在真机上编译问题,不知道是缺少引入库还是什么原因,3q
/Users/ios/Library/Developer/Xcode/DerivedData/AWLive-ajpeezoahadryvbknuefaphvixhy/Build/Intermediates/GPUImage.build/Debug-iphoneos/Documentation.build/Script-BC552B3A1558C6FC001F3FFA.sh: line 5: /usr/local/bin/appledoc: No such file or directory

**Comment by hardman** [comment]
请参考这个：http://www.jianshu.com/p/954fbd9b2c96

**Comment by ryokinki** [comment]
sorry,我就是自学的.大意了.
从代码风格以及逻辑,流程图等个方面来看,写的是非常好的,自己摸索了直播大概快半年了,一直算似懂非懂的,3q代码给了很清晰明了,说明应该怎么做.非常有实际意义
