### ISSUE TITLE
With landscape rotation on screen, the pushed stream shows distortion as attached.

### ISSUE THREAD

**Issue by jjksam** [hardman/AWLive#6]
With landscape rotation on screen, the pushed stream shows distortion as attached.
I've change the init to this.
_captureManager.videoConfig.orientation = UIInterfaceOrientationLandscapeRight;

Attached image is a black pencil on white desk.
<img width="180" alt="rotate" src="https://cloud.githubusercontent.com/assets/1285799/24130018/30ed2e32-0e21-11e7-91db-2f01028c092e.png">

**Comment by jjksam** [comment]
It's no need to rotate the image, it will be slower, we just need to set the [AVCaptureConnection setVideoOrientation:AVCaptureVideoOrientationLandscapeRight] or 

    //屏幕方向
    if (self.videoConfig.orientation == UIInterfaceOrientationLandscapeRight) {
        _videoCamera.outputImageOrientation = UIInterfaceOrientationLandscapeRight;
    } else {
        _videoCamera.outputImageOrientation = UIInterfaceOrientationPortrait;
    }

**Comment by hardman** [comment]
已解决
